; This testcase tests the program repository pruning pass. If the global
; variables or functions have been defined in the database 'clang.db', they
; will change from the definition to declaration.
;
; The testcase includes three steps:
; Step 1: Generate the repo IR code which contains the TicketNode metadata;
; Step 2: Create the database 'clang.db' which contains all Tickets.
; Step 3: Run the ProgramRepositoryPrunningPass to optimise the repo IR code
;         which is generated by Step 1;

; RUN: rm -f %t.db
; RUN: env REPOFILE=%t.db opt -mtriple="x86_64-pc-linux-gnu-repo" -O0 -S %s -o %t
; RUN: env REPOFILE=%t.db llc -mtriple="x86_64-pc-linux-gnu-repo" -filetype=obj %t
; RUN: env REPOFILE=%t.db opt -mtriple="x86_64-pc-linux-gnu-repo" -O0 -S %s | FileCheck %s

target triple = "x86_64-pc-linux-gnu-elf"

;CHECK: @c = available_externally global i32 8, align 4
$c = comdat any
@c = global i32 8, align 4, comdat($c)
;CHECK: @a = available_externally global i32 1, align 4
$a = comdat exactmatch
@a = global i32 1, align 4, comdat($a)
;CHECK: @b = available_externally global i32 1, align 4
$b = comdat largest
@b = internal global i32 1, comdat, align 4, comdat($b)

;CHECK: define available_externally i8* @me()
$me = comdat noduplicates
define linkonce_odr i8* @me() comdat($me) {
entry:
  ret i8* bitcast (i8* ()* @me to i8*)
}

;CHECK: define available_externally i32 @foo()
define internal i32 @foo() {
entry:
  %0 = load i32, i32* @a, align 4
  %inc = add nsw i32 %0, 1
  store i32 %inc, i32* @a, align 4
  store i32 2, i32* @b, align 4
  store i32 2, i32* @c, align 4
  %1 = load i32, i32* @a, align 4
  ret i32 %1
}

;CHECK: define available_externally i32 @bar()
define i32 @bar() {
entry:
  %call = call i32 @foo()
  ret i32 %call
}

;CHECK:      !TicketNode(name: "c", digest: [16 x i8] c"{{.*}}", linkage: external, pruned: true)
;CHECK: !TicketNode(name: "a", digest: [16 x i8] c"{{.*}}", linkage: external, pruned: true)
;CHECK: !TicketNode(name: "b", digest: [16 x i8] c"{{.*}}", linkage: internal, pruned: true)
;CHECK: !TicketNode(name: "me", digest: [16 x i8] c"{{.*}}", linkage: linkonce_odr, pruned: true)
;CHECK: !TicketNode(name: "foo", digest: [16 x i8] c"{{.*}}", linkage: internal, pruned: true)
;CHECK: !TicketNode(name: "bar", digest: [16 x i8] c"{{.*}}", linkage: external, pruned: true)
